apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: companybackend
  name: companybackend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: companybackend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: companybackend
    spec:
      containers:
        - args:
            - bash
            - -c
            - python check_db.py --service-name companydb --ip companydb --port 3306 && python manage.py runserver 0.0.0.0:8030
          image: individualsem6.azurecr.io/companybackend:latest
          name: companybackend
          ports:
            - containerPort: 8030
              protocol: TCP
          envFrom:
          - configMapRef:
              name: companybackend-cm0
          volumeMounts:
            - mountPath: /app/config
              name: companybackend-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: companybackend-cm0
          name: companybackend-cm0
