apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: companybackend
  name: companybackend
spec:
  ports:
    - name: "8030"
      port: 8030
      targetPort: 8030
  selector:
    io.kompose.service: companybackend
