apiVersion: v1
data:
  SECRET_KEY: django-insecure-$2oa+3+b&91t+a4_xl66qa-w==8welp$rbf5^nsouz@8j0a#3r
  DB_NAME: individualcompanydb
  DB_USER: quinncompanies
  DB_PASS: companypass
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: companybackend
  name: companybackend-cm0
