apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: companydb
  name: companydb
spec:
  ports:
    - name: "3302"
      port: 3302
      targetPort: 3306
  selector:
    io.kompose.service: companydb
