apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: companydb
  name: companydb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: companydb
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: companydb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: individualcompanydb
            - name: MYSQL_HOST
              value: companydb
            - name: MYSQL_PASSWORD
              value: companypass
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: companypass
            - name: MYSQL_USER
              value: quinncompanies
          image: mariadb:10.9
          name: companydb
          ports:
            - containerPort: 3306
              protocol: TCP
      restartPolicy: Always
