name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r companyservice/requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        python manage.py test companyservice

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: myACR.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t individualsem6.azurecr.io/companybackend:latest .
        docker push individualsem6.azurecr.io/companybackend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.14'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up AKS context
      run: az aks get-credentials --resource-group LinkedTinderGroup --name individualsem6cluster

    - name: Deploy to AKS
      run: |
        kubectl apply -f companyservice/kubernetes/deployment.yaml
        kubectl apply -f companyservice/kubernetes/service.yaml
